---
# handlers file for slacko


- name: "ntpupdate"
  ansible.builtin.command:
     cmd: "{{ hora }}"


- name: "ntp"
  community.general.timezone:
    name: America/Sao_Paulo
    environment: "{{ env }}"
  

- name: "restart mongodb"
  systemd:
    name: mongodb
    state: started
    enable: yes
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_DATABASE=auth
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - '27017:27017'

- name: "copy.service"
  ansible.builtin.service:
    name: slacko-api
    state: reloaded
    enabled: yes
  tags: 
     - start.service

- name: "start.service"
  ansible.builtin.systemd:
     state: restarted
     name: slacko-api
     enabled: yes
     masked: no
     daemon_reload: yes
     daemon_reexec: yes
  tags: start


- name: "line"
  ansible.builtin.lineinfile:
      path: /opt/slacko-api/lineinfile.txt
      regexp: '^opt'
      insertafter: '^opt'
      line: '/opt/slacko-api/ teste'

- name: "ip"
  ansible.builtin.lineinfile:
      path: /etc/mongodb.conf
      regexp: '^127.0.0.1$'
      insertafter: '^1'
      line: 'bind_ip = 0.0.0.0'


- name: "api"
  fail: 
  when: "'running' not in webpage.content"

  

   












    
