---
# tasks file for slacko



  - name: Clone a repo with separate git directory
    ansible.builtin.git:
      repo: "{{ gitpath }}"
      dest: "{{ path }}"
      force: yes
    tags:
      - gitclone


  - name: Instalar NTP
    apt:
       name: ntp
       state: present
    notify:
       - ntp
       - crond
       - env
    tags:
       - ntp   
     

  - name: copiar configuração do ntp
    copy:
        src: ntp.conf
        dest: "{{ ntppath }}"

    tags: 
      - horacerta
     

  - name: Instalaçao do MongoDB
    apt: 
      name: mongodb
      state: present
      update_cache: yes

    tags:
        - mongodb
    notify:
        - restart mongodb
        - ip


  - name: Instalaço dos requerimentos do Python
    pip:
      requirements: /opt/slacko-api/requeriments.txt
    tags: 
      - python


  - name: Criar o diretório pela variável do path
    file:
        path: "{{ path }}"
        state: directory
        owner: root
        group: root 
        mode: 0755 
    tags: path

#essa copia sobreescreve o arquivo clonado antes - em uso para teste do mdulo template
  - name: Copiar o script .sh parametrizavel
    template:
        src: slacko/templates/slacko-api.sh
        dest: "{{ path }}"
        owner: root
        group: root
        mode: 0755
    tags: 
      - script



  - name: Copiar arquivo que transforma script em service
    copy:
      src: slacko-api.service
      dest: /etc/systemd/system
      owner: root
      group: root
    notify:
      - copy.service
      - start.service
    tags: 
      - copy.service


  - name: Instalar docker e dependencias
    apt:
        name: python3-pip, docker.io
        state: present

  - name: Iniciar o Docker
    service:
      name: docker
      state: started
    become: true  

  - name: Install docker python module
    pip:
        name: docker


  - name: Criar o container do mongodb express
    docker_container:
      name: mongoexpress
      image: mongo-express:0.54.0
      state: started
      restart: yes
      network_mode: host      
      ports:
          - '8081:8081'


      env: 
        ME_CONFIG_MONGODB_ADMINUSERNAME: admin
        ME_CONFIG_MONGODB_ADMINPASSWORD: pass
        ME_CONFIG_MONGODB_SERVER: 10.0.0.11
#        
 
    become: true
    tags: 
      - deploy

  
  - name: copiar arquivo parametrizvel para modificar
    copy:
        src: lineinfile.txt
        dest: "{{ path }}"

    tags: 
      - line
    notify:
      - line

  - name: testar API
    uri: 
      url: http://10.0.0.11:8000/healthcheck
      method: GET
      return_content: yes
      body_format: json
    register: webpage
    tags: 
      - api
      



  
  
    


